version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: wedding_registry
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    ports:
      - "5000:5000"

  mongo:
      image: mongo
      restart: always
      ports:
          - "27017:27017"
      environment:
          - MONGO_INITDB_ROOT_USERNAME=root
          - MONGO_INITDB_ROOT_PASSWORD=example

  mongo-express:
      image: mongo-express
      restart: always
      ports:
          - "8081:8081"
      environment:
          - ME_CONFIG_MONGODB_ADMINUSERNAME=root
          - ME_CONFIG_MONGODB_ADMINPASSWORD=example
volumes: 
  mongodb: